version: "3.4"

x-common: &common
  stdin_open: true
  tty: true
  restart: unless-stopped
  networks:
    - cx_analysis

x-django-build: &django-build
  build:
    context: .
    dockerfile: ./Dockerfile.dev

services:
  chrome:
    image: selenium/node-chrome:4.2.1-20220531
    container_name: cx_analysis-sc01
    shm_size: 2gb
    ports:
      - "7900:7900"
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    depends_on:
      - selenium-hub
    <<: *common

  django:
    <<: *django-build
    container_name: cx_analysis-dc01
    ports:
      - "8000:8000"
    env_file:
      - ./config/env/test/.django
    volumes:
      - ./:/code
      - cx_analysis_static_volume:/code/static
      - cx_analysis_media_volume:/code/media
    depends_on:
      - postgres
      - redis
    <<: *common

  firefox:
    image: selenium/node-firefox:4.2.1-20220531
    container_name: cx_analysis-sf01
    shm_size: 2gb
    ports:
      - "7901:7900"
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    <<: *common

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    container_name: cx_analysis-fe01
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    env_file:
      - ./config/env/test/.frontend
    depends_on:
      - django
    <<: *common

  postgres:
    image: postgres:13.3-alpine
    container_name: cx_analysis-pc01
    env_file:
      - ./config/env/test/.postgres
    ports:
      - "5432:5432"
    volumes:
      - cx_analysis_postgres_data:/var/lib/postgresql/data/
    <<: *common

  redis:
    image: redis:6.2-alpine
    container_name: cx_analysis-rc01
    volumes:
      - cx_analysis_redis_data:/data
    <<: *common

  selenium-hub:
    image: selenium/hub:4.2.1-20220531
    container_name: cx_analysis-sh01
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    depends_on:
      - frontend
    <<: *common

networks:
  cx_analysis:
    driver: bridge

volumes:
  cx_analysis_postgres_data:
  cx_analysis_redis_data:
  cx_analysis_static_volume:
  cx_analysis_media_volume:
